spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: between_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: between_route
          uri: https://www.baidu.com
          predicates:
            - Query=url,qq

# 应用服务 WEB 访问端口
server:
  port: 88